### ISSUE TITLE
Not opening local fb2 on Linux

### ISSUE THREAD

**Issue by alexykot** [tymofij/fb2reader#8]
For some reason this plugin installed in Firefox on Arch Linux does not open the `.fb2` files. I do have an unzipped local `.fb2` file, but on attempting to open it in FF via `Ctrl+O` it only offers to save it or open with another application. Selecting "Firefox" that "another application" makes it go into infinite loop of opening new tabs with same save-or-open dialog, but no FB2 rendering actually happening.

**Comment by monakhv** [comment]
The same issue on Fedora 30.

**Comment by tymofij** [comment]
In Linux .fb2 files are associated with MIME type `application/x-fictionbook+xml` but Firefox refuses to do anything with those files. The extension never gets a chance, [bug 1341341](https://bugzilla.mozilla.org/show_bug.cgi?id=1341341). To make Firefox accept it, we must associate those files with `text/xml` MIME. (doc [ExternalHelperAppService](http://web.archive.org/web/20210327221422/https://developer.mozilla.org/en-US/docs/Mozilla/How_Mozilla_determines_MIME_Types#externalhelperappservice))

Solution
--------

Create `~/.local/share/mime/packages/fictionbook.xml` with content
```
<?xml version="1.0"?>
<mime-info xmlns='http://www.freedesktop.org/standards/shared-mime-info'>
  <mime-type type="text/xml">
    <glob pattern="*.fb2"/>
    <magic priority="99">
      <match type="string" value="&lt;FictionBook" offset="0:256"/>
    </magic>
  </mime-type>
</mime-info>
```

and run 
```
update-mime-database ~/.local/share/mime
```

after that check that the mime-type has been updated, run
```
xdg-mime query filetype some_book_file.fb2
```
it should output `text/xml`. Or see file properties in Nautilus, it should be "XML document".

Snap
----
This solution **does not work** for Snap Firefox packages.

PS
--
Funnily, the issue arises exactly because Linux _knows_ about .fb2 document type unlike MacOS/Windows which do not, and serve it as some unknown `text/xml`.
